<template><div><h1 id="what-is-black-jack-🫡" tabindex="-1"><a class="header-anchor" href="#what-is-black-jack-🫡" aria-hidden="true">#</a> What is black jack? 🫡</h1>
<h2 id="history" tabindex="-1"><a class="header-anchor" href="#history" aria-hidden="true">#</a> History</h2>
<p>Blackjack, also known as twenty-one or Pontoon, is one of the most popular casino card games in the world. Much of blackjack's popularity is due to the mix of chance with elements of skill, and the publicity that surrounds card counting (keeping track of which cards have been played since the last shuffle). Blackjack's precursor was vingt-et-un (&quot;twenty-one&quot;), which originated in French casinos around 1700, and did not offer the 3:2 bonus for a two-card 21.</p>
<p>When blackjack was first introduced in the United States it was not very popular, so gambling houses tried offering various bonus payouts to get the players to the tables. One such bonus was a 10-to-1 payout if the player's hand consisted of the ace of spades and a black Jack (either the Jack of clubs or the Jack of spades). This hand was called a &quot;blackjack&quot; and the name stuck to the game even though the bonus payout was soon abolished. As the game is currently played, a &quot;blackjack&quot; may not necessarily contain a jack at all.</p>
<h2 id="rule" tabindex="-1"><a class="header-anchor" href="#rule" aria-hidden="true">#</a> Rule</h2>
<p>The goal of each player is to beat the dealer by having the higher, unbusted hand. Note that if the player busts he loses, even if the dealer also busts (therefore Blackjack favors the dealer). If both the player and the dealer have the same point value, it is called a &quot;push&quot;, and neither player nor dealer wins the hand. Each player has an independent game with the dealer, so it is possible for the dealer to lose to one player, but still beat the other players in the same round.</p>
</div></template>


